### ISSUE TITLE
Interval parameter on ASP endpoint throwing 404 for 'day', 'week' or 'year'

### ISSUE THREAD

**Issue by bilbof** [chartmogul/metrics-api#5]
For example:

```
curl https://api.chartmogul.com/v1/metrics/asp \
-X GET \
-u 41e70131daaf56b516f32a38c8b8628d:187583e8b9d77eadae8c6a1db83f7875 \
-d interval=week \
-d start-date=2015-10-01 \
-d end-date=2015-11-01
```

**Comment by bilbof** [comment]
Need to update here when completed: https://github.com/chartmogul/metrics-api/blob/master/API-Documentation/api.md#supported-parameters-7

**Comment by kkdoo** [comment]
@bilbof Documentation was wrong https://github.com/chartmogul/metrics-api/commit/ddf6debdd152dcd6bc3e4b1336d96684e9935aad

**Comment by bilbof** [comment]
@kkdoo :+1: closing
