### ISSUE TITLE
customers/{id}/plans endpoint not supported

### ISSUE THREAD

**Issue by bilbof** [chartmogul/metrics-api#6]
### Steps to reproduce:

Try

```
curl https://api.chartmogul.com/v1/customers/7283428/plans \
-X GET \
-u 41e70131daaf56b516f32a38c8b8628d:187583e8b9d77eadae8c6a1db83f7875
```

Response

404

### Next steps

@kkdoo asking @ytvinay if we want to support this.

**Comment by bilbof** [comment]
cc @kkdoo

**Comment by bilbof** [comment]
Update here when ready: https://github.com/chartmogul/metrics-api/blob/master/API-Documentation/api.md#customersidplans (either remove the warning or the whole section there).

**Comment by bilbof** [comment]
Moved docs here. We can add them if they're needed later:

### /customers/{id}/plans

:warning: Currently not supported. See https://github.com/chartmogul/metrics-api/issues/6.

Returns an array of entries containing the given customer's plans.

#### Supported Parameters

none

#### Example Request

```
https://api.chartmogul.com/v1/customers/{12345}/plans
```

#### Example cURL Request

```
curl https://api.chartmogul.com/v1/customers/7283428/plans \
-X GET \
-u 41e70131daaf56b516f32a38c8b8628d:187583e8b9d77eadae8c6a1db83f7875
```

#### Example Response

```JSON
{
	"entries":[
		{
			"arpa": 30718.7199565509
			"arr": 5160744.952700544
			"asp": 2762.66666666667
			"customer-churn-rate": 0
			"customers": 14
			"date": "2015-05-01"
			"ltv": 0
			"mrr": 430062.079391712
			"mrr-churn-rate": 5.5
		}
	]
}
```

**Comment by ytvinay** [comment]
Closing issue until we decide to include the endpoint
